#-----------
#
# HowLong CI
#
#-----------

# This is a basic workflow to help you get started with Actions

name: HowLong-CI

env:
  PROJECT_PATH: "HowLong/HowLong/HowLong.csproj"
  CONFIGURATION: "Release"
  COMMIT_FULL_NAME: "HowLong-${{ github.sha }}"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  clean:
    runs-on: windows-latest
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Clean Project
      run: |
        echo "Before pipeline ${{ env.COMMIT_FULL_NAME }}"
        dotnet clean ${{ env.PROJECT_PATH }} -c ${{ env.CONFIGURATION }}

  restore:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    needs: [ clean ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Restore nuget
      run: nuget restore ${{ env.PROJECT_PATH }}
  
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    needs: [ restore ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Build Project
      run: dotnet build ${{ env.PROJECT_PATH }} -c ${{ env.CONFIGURATION }}
